---
name: Update-docs
on:              # yamllint disable-line rule:truthy
  push:
    branches:
      - main
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pushes Readme file
        uses: dmnemec/copy_file_to_another_repo_action@8f2c47e3b3b1f8e6c73947f91e68c72a9f5aef31
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_TOKEN_GITHUB: ${{ secrets.ARC_DOCS_API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          destination_repo: 'sourcefuse/arc-docs'
          destination_folder: 'docs/arc-iac-docs/modules/terraform-aws-arc-sns'
          user_email: 'github-actions@github.com'
          user_name: ${{ github.actor }}
          commit_message: ${{ github.event.head_commit.message }}

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_TOKEN_GITHUB: ${{ secrets.ARC_DOCS_API_TOKEN_GITHUB }}
        with:
          source-directory: 'static'
          destination-github-username: 'sourcefuse'
          destination-repository-name: 'arc-docs'
          target-directory: 'docs/arc-iac-docs/modules/terraform-aws-arc-sns/static'
          user-email: 'github-actions@github.com'
          user-name: ${{ github.actor }}
          target-branch: main
          commit-message: ${{ github.event.head_commit.message }}

      - name: Pushes Module Usage Guide
        uses: cpina/github-action-push-to-another-repository@76a67d3f4bb0b6f9f12aadc89e2a9e8db83db5b7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_TOKEN_GITHUB: ${{ secrets.ARC_DOCS_API_TOKEN_GITHUB }}
        with:
          source_file: 'docs/module-usage-guide/README.md'
          destination_repo: 'sourcefuse/arc-docs'
          destination_folder: 'docs/arc-iac-docs/modules/terraform-aws-arc-sns/docs/module-usage-guide'
          user_email: 'github-actions@github.com'
          user_name: ${{ github.actor }}
          commit_message: ${{ github.event.head_commit.message }}
